--[[dtMediaWiki is a darktable plugin which exports images to Wikimedia Commons
    Author: Trougnouf (Benoit Brummer) <trougnouf@gmail.com>
    Contributor: Simon Legner (simon04)

Dependencies:
* lua-sec: Lua bindings for OpenSSL library to provide TLS/SSL communication
* lua-luajson: JSON parser/encoder for Lua
* lua-multipart-post: HTTP Multipart Post helper
]]
local dt = require "darktable"
local MediaWikiApi = require "contrib/dtMediaWiki/lib/mediawikiapi"
local MetadataUI = require "contrib/dtMediaWiki/lib/metadata_ui"
require "contrib/dtMediaWiki/lib/category_search"
local placeholders = require "contrib/dtMediaWiki/lib/placeholders"
local version = 123

--[[The version number is generated by .git/hooks/pre-commit (+x)
    with the following content:
  #!/bin/sh
  NEWVERSION="$(expr "$(git log master --pretty=oneline | wc -l)" + 1)"
  sed -i -r "s/local version = [0-9]+/local version = ${NEWVERSION}/1" dtMediaWiki.lua
  git add dtMediaWiki.lua
  ]]

-- Use this _ function for translatable strings
local gettext = dt.gettext
gettext.bindtextdomain(
  "dtMediaWiki",
  dt.configuration.config_dir .. "/lua/contrib/dtMediaWiki/locale/"
)
local function translate(msgid)
  return gettext.dgettext("dtMediaWiki", msgid)
end

local function msgout(str)
  -- Use msgout(translate("STRING")) to output STRING in both the terminal and GUI
  print(str)
  dt.print(str)
end

local function dbgout(str)
  -- Use dbgout(translate("STRING")) to output STRING in the debug terminal (darktable -d lua)
  dt.print_log(str)
end

-- Preference entries
local preferences_prefix = "mediawiki"

dt.preferences.register(
  preferences_prefix,
  "cat_cam",
  "bool",
  translate("Commons: Categorize camera?"),
  translate("A category will be added with the camera information " ..
    "(eg: [[Category:Taken with Fujifilm X-E2 and XF18-55mmF2.8-4 R LM OIS]])"),
  false
)

dt.preferences.register(
  preferences_prefix,
  "desc_templates",
  "string",
  translate("Commons: Templates to be placed in {{Information |description= ...}}"),
  translate('These templates are placed in the {{Information |description= ...}} field. (comma-separated)'),
  "Description,Depicted person,en,de,fr,es,ja,ru,zh,it,pt,ar"
)

dt.preferences.register(
  preferences_prefix,
  "overwrite",
  "bool",
  translate("Commons: Overwrite existing images?"),
  translate("Existing images will be overwritten  without confirmation, otherwise the upload will fail."),
  false
)

dt.preferences.register(
  preferences_prefix,
  "authorpattern",
  "string",
  translate("Commons: Preferred author pattern"),
  translate("Determines the author value; variables are $USERNAME, $CREATOR"),
  "[[User:$USERNAME|$CREATOR]]"
)

dt.preferences.register(
  preferences_prefix,
  "namepattern",
  "string",
  translate("Commons: Preferred filename pattern"),
  translate("Determines the filename value; variables are $TITLE, $DESCRIPTION, $FILE_NAME"),
  "$TITLE ($FILE_NAME)"
)

-- Preference for allowing empty Information|description field on Commons
dt.preferences.register(
  preferences_prefix,
  "allow_empty_description",
  "bool",
  translate("Commons: Allow empty 'Information|description' on page?"),
  translate("If unchecked (default), images where both title and description metadata are empty "
    .. "will not be uploaded, as this results in an empty '{{Information|description=...}}' field "
    .. "on Wikimedia Commons. If checked, such uploads are allowed (unless the filename pattern "
    .. "specifically requires title or description)."),
  false
)

-- FIXME: can't figure enum out so using a text field in the meantime
-- see also:
-- https://docs.darktable.org/lua/stable/lua.api.manual/darktable/darktable.preferences/#darktablepreferencesregister
dt.preferences.register(
  preferences_prefix,
  "default_license",
  "string",
  translate("Commons: Default license"),
  translate("Default license for images uploaded to Wikimedia Commons (eg: CC-BY-SA-4.0, CC-BY-4.0, PD, ...)"),
  "CC-BY-SA-4.0"
)

dt.preferences.register(
  preferences_prefix,
  "password",
  "string", -- TODO Use Lua password storage once in release. See https://github.com/darktable-org/darktable/pull/7508
  translate("Wikimedia password"),
  translate("Wikimedia Commons password (to be stored in plain-text!)"),
  ""
)

dt.preferences.register(
  preferences_prefix,
  "username",
  "string",
  translate('Wikimedia username'),
  translate("Wikimedia Commons username"),
  ""
)

local namepattern_default = dt.preferences.read(preferences_prefix, "namepattern", "string")

local namepattern_widget =
    dt.new_widget("entry") {
      tooltip = table.concat(
        {
          translate("Determines the `File:` page name on Wikimedia Commons."),
          "",
          translate("Placeholder syntax:"),
          translate("  <dateYYYYMMDD> - capture date as YYYYMMDD"),
          translate("  <title> - title from image metadata"),
          translate("  <fileName> - original filename using the export extension"),
          translate("  and other placeholders available in the selector below"),
          "",
          translate("Legacy variables are still supported:"),
          translate("  $FILE_NAME"),
          translate("  $TITLE"),
          translate("  $DESCRIPTION")
        },
        "\n"
      ),
      text = dt.preferences.read(
        preferences_prefix,
        "namepattern",
        "string"
      ),

      reset_callback = function(self)
        self.text = namepattern_default

        dt.preferences.write(
          preferences_prefix,
          "namepattern",
          "string",
          self.text
        )
      end
    }

-----------------------------------------------------------------------
-- Filename placeholder selector
-----------------------------------------------------------------------

local filename_placeholder_defs =
  placeholders.list_enabled()

local filename_placeholder_names = {}

for _, def in ipairs(filename_placeholder_defs) do
  table.insert(
    filename_placeholder_names,
    def.name
  )
end

local filename_placeholder_widget =
  dt.new_widget("combobox") {
    label = translate("Insert placeholder"),
    tooltip = translate(
      "Append a placeholder into the Wikimedia Commons filename pattern."
    ),
    changed_callback = function(widget)

      local index = widget.selected

      if not index or index == 0 then
        return
      end

      local name =
        filename_placeholder_names[index]

      if not name then
        return
      end

      namepattern_widget.text =
        (namepattern_widget.text or "")
        .. "<" .. name .. ">"

      widget.selected = 0
    end
  }

for _, def in ipairs(filename_placeholder_defs) do

  local display =
    tostring(def.group or "") ..
    " — <" ..
    tostring(def.name) ..
    ">"

  filename_placeholder_widget[
    #filename_placeholder_widget + 1
  ] = display

  table.insert(
    filename_placeholder_names,
    def.name
  )
end

-- language widget shown in lighttable export
local language_widget =
    dt.new_widget("entry") {
      text = "en",
      tooltip = translate("Description language code. Additional descriptions may be added with tag "
        .. "{{Description|language_code|description_text}} or any of the templates listed in "
        .. "the desc_template setting."),
      reset_callback = function(self)
        self.text = "en"
      end
    }

-- Generate image name
local function make_image_name(image, tmp_exp_path)

  local outname_pattern = namepattern_widget.text

  if outname_pattern == nil or outname_pattern == "" then
    outname_pattern = namepattern_default
  end

  local ext =
    tmp_exp_path:match("%.([^./\\]+)$") or ""

  local basename =
    tostring(image.filename or "")
      :gsub("\\", "/")
      :match("([^/]+)$") or ""

  basename =
    basename:match("^(.*)%.[^.]+$") or basename

  ---------------------------------------------------------------------
  -- Legacy dtMediaWiki placeholders
  ---------------------------------------------------------------------

  local final_outname = outname_pattern

  final_outname =
    final_outname:gsub("%$FILE_NAME", basename)

  final_outname =
    final_outname:gsub("%$TITLE", image.title or "")

  final_outname =
    final_outname:gsub(
      "%$DESCRIPTION",
      image.description or ""
    )

  ---------------------------------------------------------------------
  -- New dtMediaWiki placeholder engine
  ---------------------------------------------------------------------

  final_outname =
    placeholders.expand_filename(
      image,
      final_outname,
      {
        export_extension = ext
      }
    )

  ---------------------------------------------------------------------
  -- Safety fallback
  ---------------------------------------------------------------------

  if final_outname == ""
      or final_outname:match("^%s*$") then

    dt.print_log(
      translate(
        "Filename pattern resulted in an empty name, " ..
        "falling back to input image basename."
      )
    )

    final_outname = basename
  end

  ---------------------------------------------------------------------
  -- Add export extension unless already present
  ---------------------------------------------------------------------

  if ext ~= "" then

    local existing_ext =
      final_outname:match("%.([^./\\]+)$")

    if not existing_ext
        or existing_ext:lower() ~= ext:lower() then

      final_outname =
        final_outname .. "." .. ext
    end
  end

  return final_outname
end

-- Round to 1 decimal, remove useless .0's and convert number to string. Ensure that "." decimal separator is used
local function fmt_flt(num)
  return string.format("%.1f", num):gsub(",", "."):gsub("%.0", "")
end

-- Get description field from the description (or title) metadata
local function get_description(image)
  if image.description ~= "" then
    return image.description
  else
    return image.title -- Fallback to title if description is empty
  end
end

local function split(astring)
  local sep, fields = ",", {}
  local pattern = string.format("([^%s]+)", sep)
  astring:gsub(pattern, function(c) fields[#fields + 1] = c end)
  return fields
end

-- get description templates which needs to be added to {{Information| description=...}}
local function get_intl_descriptions(image, discarded_tags)
  local desc_templates = split(dt.preferences.read(preferences_prefix, "desc_templates", "string"))
  local intl_descriptions = ""
  for _, tag in pairs(dt.tags.get_tags(image)) do
    if tag ~= 0 then -- workaround for dt bug #9715
      local tagstr = tag.name
      for _, dtemplate in pairs(desc_templates) do
        if tagstr:sub(1, #dtemplate + 3) == '{{' .. dtemplate .. '|' then
          intl_descriptions = intl_descriptions .. tagstr
          discarded_tags[tagstr] = true
        end
      end
    end
  end
  return intl_descriptions
end


-- Get other fields that are then added to the Information template (TODO document this feature)
local function get_other_fields(image, discarded_tags)
  local other_fields = ''
  for _, tag in pairs(dt.tags.get_tags(image)) do
    if tag ~= 0 then -- workaround for dt bug #9715
      local tagstr = tag.name
      if string.sub(tagstr, 0, 20) == '{{Information field|'
          or string.sub(tagstr, 0, 7) == '{{InFi|' then
        other_fields = other_fields .. tagstr
        discarded_tags[tagstr] = true
      end
    end
  end
  return other_fields
end

local function substitute_keywords(string, image)
  local username = dt.preferences.read(preferences_prefix, "username", "string")
  -- Bot password logins use "User@botname", the account is "User".
  username = username:match("^(.-)@") or username
  string = string:gsub("$USERNAME", username)
  string = string:gsub("$CREATOR", image.creator or username)
  string = string:gsub("$FILE_NAME", image.filename)
  string = string:gsub("$DATETIME", image.exif_datetime_taken)
  string = string:gsub("$YEAR", image.exif_datetime_taken:sub(0, 4))
  string = string:gsub("\\comma", ",")
  return string
end


-----------------------------------------------------------------------
-- Global Commons categories
-----------------------------------------------------------------------

local global_categories_widget =
  dt.new_widget("text_view") {
    text = "",
    editable = true,

    tooltip = translate(
      "Commons categories added to every image in this export. "
      .. "Enter one category per line, without [[Category:...]]."
    )
  }

-----------------------------------------------------------------------
-- Additional Commons Wikitext
-----------------------------------------------------------------------

local additional_wikitext_widget =
  dt.new_widget("text_view") {
    text = "",
    editable = true,

    tooltip = translate(
      "Additional Wikitext added to every Commons file page "
      .. "in this export, for example {{Supported by Wikimedia Österreich}}."
    )
  }



-- get "Other versions" of this image, ie different views of the scene or duplicate
-- of this image (the latter needs to have a different title).
-- Used with the "alt:<fn>" tag;
-- matches <fn> contained in other images' filename in the current library.
-- input:
---- image: working image (dt_lua_image_t)
---- tmp_img_fn: working image temporary export filename (string)
-- output:
---- gallery following "Other versions = " on the image page, or an empty string (string)
-- TODO document this feature
local function get_alt_images(image, tmp_img_fn)
  local alts = {}
  for _, tag in pairs(dt.tags.get_tags(image)) do
    if tag ~= 0 then -- workaround for dt bug #9715
      if string.sub(tag.name, 1, 4) == "alt:" then
        table.insert(alts, string.sub(tag.name, 5))
      end
    end
  end
  if next(alts) == nil then
    return ""
  end
  local altcode = { "<gallery showfilename=yes>" }
  for _, img in pairs(dt.collection) do
    dbgout(translate("dtMediaWiki.get_alt_images: looking at ") .. img.filename)
    for _, altimg in pairs(alts) do
      dbgout(translate("dtMediaWiki.get_alt_images: looking for ") .. altimg)
      if string.find(img.filename, altimg) then
        local alt_fn = make_image_name(img, tmp_img_fn)
        table.insert(altcode, alt_fn)
        dbgout(translate("dtMediaWiki.get_alt_images: found ") .. alt_fn)
      end
    end
  end
  table.insert(altcode, '</gallery>')
  return table.concat(altcode, "\n")
end

-- helper to get the license from image rights or default preference
local function get_license(image)
  local license = image.rights
  if license == "" then
    license = dt.preferences.read(preferences_prefix, "default_license", "string")
  end
  return license
end

local function trim(value)
  return tostring(value or "")
    :gsub("^%s+", "")
    :gsub("%s+$", "")
end

-- TODO unused, superseded by placeholders.parse_categories
local function parse_commons_categories(text) -- luacheck: ignore

  local categories = {}

  -- Categories may be separated by semicolons or newlines.
  -- Examples:
  --
  --   Category one;Alice Albert;WikiCon 2026
  --
  -- or:
  --
  --   Category one
  --   Alice Albert
  --   WikiCon 2026

  text = tostring(text or "")

  -- Treat line endings exactly like semicolons.
  text = text:gsub("\r\n", ";")
  text = text:gsub("[\r\n]", ";")

  for item in text:gmatch("[^;]+") do

    item = trim(item)

    -- Be liberal about accepting complete Commons category syntax.
    item = item:gsub(
      "^%[%[[Cc]ategory:%s*",
      ""
    )

    item = item:gsub("%]%]$", "")
    item = trim(item)

    if item ~= "" then
      table.insert(categories, item)
    end
  end

  return categories
end

local function get_new_commons_categories(image)

  local categories = {}
  local seen = {}

  local function add(category)

    category = trim(category)

    if category ~= ""
        and not seen[category] then

      seen[category] = true

      table.insert(
        categories,
        category
      )
    end
  end

  -- Per-image Commons categories
  -- TODO stored_value is unused, the inner loop repeats the same lookup
  for _, stored_value in ipairs( -- luacheck: ignore
    placeholders.get_categories(image)
  ) do

    for _, category in ipairs(
      placeholders.get_categories(image)
    ) do
      add(category)
    end
  end

  -- Global Commons categories
  for _, category in ipairs(
    placeholders.parse_categories(
      global_categories_widget.text
    )
  ) do
    add(category)
  end

  return categories
end

local function get_dtmediawiki_descriptions(image)

  local descriptions = {}

  local de =
    trim(
      placeholders.get_metadata(
        image,
        "description_de"
      )
    )

  local en =
    trim(
      placeholders.get_metadata(
        image,
        "description_en"
      )
    )

  if de ~= "" then
    table.insert(
      descriptions,
      "{{de|1=" .. de .. "}}"
    )
  end

  if en ~= "" then
    table.insert(
      descriptions,
      "{{en|1=" .. en .. "}}"
    )
  end

  for _, description in ipairs(
    placeholders.get_field(
      image,
      "description_other"
    )
  ) do

    description = trim(description)

    if description ~= "" then
      table.insert(
        descriptions,
        description
      )
    end
  end

  return table.concat(descriptions, "\n")
end

-- Get per-image values of a multi-value metadata field, trimmed and
-- without empty entries.
local function get_field_values(image, name)

  local result = {}

  for _, value in ipairs(
    placeholders.get_field(image, name)
  ) do

    value = trim(value)

    if value ~= "" then
      table.insert(result, value)
    end
  end

  return result
end

-- Other fields from the metadata panel. Wikidata items are shown as
-- an additional {{Information field}}.
local function get_dtmediawiki_other_fields(image)

  local fields =
    get_field_values(image, "other_fields")

  for _, item in ipairs(
    get_field_values(image, "wikidata")
  ) do

    if item:match("^[Qq]%d+$") then
      item = "{{Q|" .. item:upper() .. "}}"
    end

    table.insert(
      fields,
      "{{Information field|name=Wikidata|value=" .. item .. "}}"
    )
  end

  return table.concat(fields)
end

-- Other versions from the metadata panel merged with the gallery
-- generated from "alt:" tags.
local function get_other_versions(image, tmp_img_fn)

  local gallery =
    get_alt_images(image, tmp_img_fn)

  local files = {}

  for _, file in ipairs(
    get_field_values(image, "other_versions")
  ) do

    file = trim(
      file:gsub("^%[%[", "")
          :gsub("%]%]$", "")
          :gsub("^[Ff]ile:", "")
    )

    if file ~= "" then
      table.insert(files, file)
    end
  end

  if #files == 0 then
    return gallery
  end

  if gallery == "" then
    return "<gallery showfilename=yes>\n"
      .. table.concat(files, "\n")
      .. "\n</gallery>"
  end

  return (gallery:gsub(
    "</gallery>$",
    function()
      return table.concat(files, "\n") .. "\n</gallery>"
    end
  ))
end

-- Templates from the metadata panel, wrapped in {{...}} if needed.
local function get_dtmediawiki_templates(image)

  local templates = {}

  for _, template in ipairs(
    get_field_values(image, "templates")
  ) do

    if template:sub(1, 2) ~= "{{" then
      template = "{{" .. template .. "}}"
    end

    table.insert(templates, template)
  end

  return templates
end

-- Generate an image page with all required info from tags, metadata, and such.
local function make_image_page(image, tmp_img_fn)
  local discarded_tags = {}
  local imgpg = { "=={{int:filedesc}}==\n{{Information" }

local new_descriptions =
  get_dtmediawiki_descriptions(image)

if new_descriptions ~= "" then

  table.insert(
    imgpg,
    "|description=" .. new_descriptions
      .. get_intl_descriptions(
        image,
        discarded_tags
      )
  )
else

  -- Legacy dtMediaWiki behaviour
  table.insert(
    imgpg,
    "|description={{"
      .. language_widget.text
      .. "|1="
      .. substitute_keywords(
        get_description(image),
        image
      )
      .. "}}"
      .. get_intl_descriptions(
        image,
        discarded_tags
      )
  )

end

  local date = image.exif_datetime_taken
  date = date:gsub("(%d%d%d%d):(%d%d):(%d%d)", "%1-%2-%3") -- format date in ISO 8601 / RFC 3339
  table.insert(imgpg, "|date=" .. date)
  table.insert(imgpg, "|source={{own}}")
  local author = dt.preferences.read(preferences_prefix, "authorpattern", "string")
  author = substitute_keywords(author, image)
  table.insert(imgpg, "|author=" .. author)
  table.insert(imgpg, '|other fields = ' .. get_other_fields(image, discarded_tags)
    .. get_dtmediawiki_other_fields(image))
  table.insert(imgpg, '|other versions = ' .. get_other_versions(image, tmp_img_fn))
  table.insert(imgpg, "}}")
  if image.latitude ~= nil and image.longitude ~= nil then
    table.insert(imgpg, "{{Location |1=" .. string.gsub(image.latitude, ",", ".")
      .. " |2=" .. string.gsub(image.longitude, ",", ".") .. " }}")
  end

table.insert(
  imgpg,
  "=={{int:license-header}}=="
)

table.insert(
  imgpg,
  "{{self|" .. get_license(image) .. "}}"
)

for _, template in ipairs(
  get_dtmediawiki_templates(image)
) do
  table.insert(imgpg, template)
end

-----------------------------------------------------------------------
-- Additional global Wikitext
-----------------------------------------------------------------------

local additional_wikitext =
  trim(additional_wikitext_widget.text)

if additional_wikitext ~= "" then
  table.insert(
    imgpg,
    additional_wikitext
  )
end

-----------------------------------------------------------------------
-- Existing dtMediaWiki tag processing
-----------------------------------------------------------------------

for _, tag in pairs(dt.tags.get_tags(image)) do
    if tag ~= 0 then -- workaround for dt bug #9715
      local subbed_tag = substitute_keywords(tag.name, image)
      if string.sub(subbed_tag, 1, 9) == "Category:" then
        table.insert(imgpg, "[[" .. subbed_tag .. "]]")
      elseif subbed_tag:sub(1, 2) == "{{" and not discarded_tags[subbed_tag] then
        table.insert(imgpg, subbed_tag)
      end
    end
  end

for _, category in ipairs(
  get_new_commons_categories(image)
) do

  table.insert(
    imgpg,
    "[[Category:" .. category .. "]]"
  )

end

  if dt.preferences.read(preferences_prefix, "cat_cam", "bool") then
    if image.exif_model ~= "" then
      local model = image.exif_maker:sub(1, 1) .. image.exif_maker:sub(2):lower()
      local catcam = "[[Category:Taken with " .. model .. " " .. image.exif_model
      if image.exif_lens ~= "" then
        catcam = catcam .. " and " .. image.exif_lens .. "]]"
      else
        catcam = catcam .. "]]"
      end
      table.insert(imgpg, catcam)
    end
    if image.exif_aperture then
      -- convert aperture to US_en locale and remove trailing .0 if there is any
      table.insert(imgpg, "[[Category:F-number f/" .. fmt_flt(image.exif_aperture) .. "]]")
    end
    if image.exif_focal_length ~= "" then
      table.insert(imgpg, "[[Category:Lens focal length " .. fmt_flt(image.exif_focal_length) .. " mm]]")
    end
    if image.exif_iso ~= "" then
      table.insert(imgpg, "[[Category:ISO speed rating " .. fmt_flt(image.exif_iso) .. "]]")
    end
  end
  table.insert(imgpg, "[[Category:Uploaded with dtMediaWiki]]")
  imgpg = table.concat(imgpg, "\n")
  return imgpg
end

-- comment widget shown in lighttable export
local comment_widget =
    dt.new_widget("entry") {
      text = translate("Uploaded with dtMediaWiki ") .. version,
      reset_callback = function(self)
        self.text = translate("Uploaded with dtMediaWiki ") .. version
      end
    }

-----------------------------------------------------------------------
-- Global Commons categories
-----------------------------------------------------------------------

local function parse_categories(text)

  local result = {}

  for line in tostring(text or ""):gmatch("[^\r\n]+") do

    line =
      line:gsub("^%s+", "")
          :gsub("%s+$", "")

    -- Be forgiving if the user entered Commons syntax.
    line =
      line:gsub(
        "^%[%[[Cc]ategory:%s*",
        ""
      )

    line =
      line:gsub("%]%]$", "")

    if line ~= "" then
      table.insert(result, line)
    end
  end

  return result
end

local function get_commons_categories(image)

  local result = {}
  local seen = {}

  local function add(value)

    value =
      tostring(value or "")
        :gsub("^%s+", "")
        :gsub("%s+$", "")

    if value ~= "" and not seen[value] then
      seen[value] = true
      table.insert(result, value)
    end
  end

  ---------------------------------------------------------------------
  -- Image-specific categories
  ---------------------------------------------------------------------

  for _, category in ipairs(
    placeholders.get_categories(image)
  ) do
    add(category)
  end

  ---------------------------------------------------------------------
  -- Global export categories
  ---------------------------------------------------------------------

  for _, category in ipairs(
    parse_categories(
      global_categories_widget.text
    )
  ) do
    add(category)
  end

  return result
end

-- TODO unused, make_image_page builds the category links itself
local function make_commons_categories(image) -- luacheck: ignore

  local lines = {}

  for _, category in ipairs(
    get_commons_categories(image)
  ) do

    table.insert(
      lines,
      "[[Category:" .. category .. "]]"
    )
  end

  return table.concat(lines, "\n")
end

-----------------------------------------------------------------------
-- Additional Commons Wikitext
-----------------------------------------------------------------------

-- TODO unused, make_image_page reads additional_wikitext_widget itself
local function get_additional_wikitext() -- luacheck: ignore

  local text =
    tostring(
      additional_wikitext_widget.text
      or ""
    )

  text =
    text:gsub("^%s+", "")
        :gsub("%s+$", "")

  return text
end

-- check if extension is supported (when using the copy mode we only get the extension at this point)
local function _register_storage_store_final_format_check(fn)
  local extension = fn:match("[^.]+$"):lower()
  if extension ~= "jpg" and extension ~= "png" and extension ~= "tif" and extension ~= "webp" then
    -- TODO would be nice to assert that copy mode is used
    -- TODO add avif when this ticket will be solved https://phabricator.wikimedia.org/T257719
    msgout(translate(
      ("dtMediaWiki._register_storage_store_final_format_check warning: "
        .. "using copy mode from an unsupported image format is known to cause a crash.")))
    msgout(
      translate("Error: ") .. fn ..
      translate(" has an unsupported extension, won't be exported to Wikimedia Commons in copy mode")
    )
    return false
  end
  return true
end

--This function is called once for each exported image
local function register_storage_store(_, image, _, tmp_exp_path, _, _, _, extra_data)
  msgout(translate("register_storage_store: exporting the following image:"))
  msgout(tmp_exp_path .. '(' .. image.title .. ')')
  for _, tag in pairs(dt.tags.get_tags(image)) do
    if tag == 0 then
      msgout(translate("BUG: invalid tag 0 for image ") .. image.title)
    end
  end

  local imagepage = make_image_page(image, tmp_exp_path)
  local imagename = make_image_name(image, tmp_exp_path)
  --print(imagepage)
  local success = _register_storage_store_final_format_check(tmp_exp_path)
  if success then
    success = MediaWikiApi.uploadfile(
      tmp_exp_path,
      imagepage,
      imagename,
      dt.preferences.read(preferences_prefix, "overwrite", "bool"),
      comment_widget.text
    )
  end
  if success then
    msgout(translate("exported ") .. imagename) -- that is the path also
  else
    msgout(translate("Failed to export ") .. imagename)
    extra_data["failures_count"] = extra_data["failures_count"] + 1
  end
end

--This function is called once all images are processed and all store calls are finished.
local function register_storage_finalize(_, image_table, extra_data)
  local successfully_initialized_count = 0
  for _ in pairs(image_table) do
    successfully_initialized_count = successfully_initialized_count + 1
  end

  local successfully_uploaded_count = successfully_initialized_count - extra_data["failures_count"]

  msgout(translate("exported ") .. successfully_uploaded_count .. "/" .. extra_data["init_img_cnt"] ..
    translate(" images to Wikimedia Commons"))
end

--A function called to check if a given image format is supported by the Lua storage;
--This is used to build the dropdown format list for the GUI.
local function register_storage_supported(_, format)
  local ext = format.extension
  return ext == "jpg" or ext == "png" or ext == "tif" or ext == "webp" or ext == "" -- "" is for the "copy" mode
end

--A function called before storage happens
--This function can change the list of exported functions
local function register_storage_initialize(_, _, images, _, extra_data)
  -- Persist edits still pending in the metadata panel.
  MetadataUI.save()

  local out_images = {}
  extra_data["failures_count"] = 0 -- For store() failures
  extra_data["init_img_cnt"] = #images
  local init_failures_count = 0 -- For initialize() failures

  -- This preference means "Allow the {{Information|description=...}} field on Commons to be empty"
  -- which happens if both image.title and image.description are empty.
  local allow_empty_page_content_pref = dt.preferences.read(preferences_prefix, "allow_empty_description", "bool")
  local current_namepattern = namepattern_widget.text
  if current_namepattern == nil or current_namepattern == '' then
    current_namepattern = namepattern_default
  end

  for _, img in pairs(images) do
    local is_valid_for_export = true
    local failure_reasons = {}

    -- BUG? images contain "0" value (with key 3 in tested instance) instead of dt_lua_image_t
    if type(img) == 'number' then
      is_valid_for_export = false
      table.insert(failure_reasons,
        translate("BUG: dt.register_storage.initialize sent a number instead of dt_lua_image_t in images table: ")
          .. img
      )
    else
      -- Reason 1: License
      if get_license(img) == "" then
        is_valid_for_export = false
        table.insert(failure_reasons, translate("has no rights"))
      end

      local title_empty = (img.title == nil or img.title == "")
      local description_empty = (img.description == nil or img.description == "")

      -- Reason 2: Title required by filename pattern but missing
      local filename_requires_title =
        current_namepattern:find("%$TITLE")
        or current_namepattern:find("<title>", 1, true)

      if filename_requires_title and title_empty then
        is_valid_for_export = false

      table.insert(
        failure_reasons,
        translate(
          "is missing a title, which is required by the filename pattern"
        )
      )
    end

    -- Reason 3: Description required by filename pattern but missing
    local filename_requires_description =
      current_namepattern:find("%$DESCRIPTION")
      or current_namepattern:find("<description>", 1, true)

      if filename_requires_description and description_empty then
        is_valid_for_export = false

      table.insert(
        failure_reasons,
        translate(
          "is missing a description, which is required by the filename pattern"
        )
      )
   end
      -- Reason 4: The {{Information|description=...}} field on Commons would be empty,
      -- and the preference 'allow_empty_description' (which means allow empty page content) is false.
      -- This happens if both title and description metadata are empty.
   local description_de_empty =
     trim(
       placeholders.get_metadata(
         img,
         "description_de"
       )
     ) == ""

   local description_en_empty =
     trim(
       placeholders.get_metadata(
         img,
         "description_en"
       )
     ) == ""

   if not allow_empty_page_content_pref
    and title_empty
    and description_empty
    and description_de_empty
    and description_en_empty then
         is_valid_for_export = false
         table.insert(failure_reasons, translate("is missing both title and description, resulting in an empty "
           .. "'Information|description' field on the Commons page "
           .. "(and the 'Allow empty Information|description...' preference is off)"))
      end
    end

    if not is_valid_for_export then
      init_failures_count = init_failures_count + 1
      -- TODO initial value is unused, it is always overwritten below
      local error_intro = "" -- luacheck: ignore
      if type(img) == 'number' then
         error_intro = translate("Error: ")
      else
         error_intro = translate("Error: ") .. (img.path or "Unknown image") .. " "
      end

      local unique_reasons = {}
      local seen_reasons_map = {}
      for _, reason in ipairs(failure_reasons) do
        if not seen_reasons_map[reason] then
          table.insert(unique_reasons, reason)
          seen_reasons_map[reason] = true
        end
      end

      if #unique_reasons > 0 then
        msgout(
          error_intro .. table.concat(unique_reasons, "; ") ..
          translate(", won't be exported to Wikimedia Commons")
        )
      end
    else
      table.insert(out_images, img)
    end
  end
  return out_images
end

-- Temporary Commons preview button
-- TODO unused, its entry in the export widget is commented out
local preview_button = -- luacheck: ignore
  dt.new_widget("button") {
    label = translate("Write Commons preview"),

    clicked_callback = function()

      local images = dt.gui.selection()

      if not images or #images == 0 then
        dt.print("dtMediaWiki: no image selected")
        return
      end

      MetadataUI.save()

      local image = images[1]

      -- make_image_page() needs the temporary filename only for
      -- the existing "other versions" handling.
      local preview =
        make_image_page(
          image,
          image.filename or ""
        )

      local home = os.getenv("HOME") or os.getenv("USERPROFILE") or "."
      local filename =
        home .. "/dtmediawiki-commons-preview.txt"

      local f, err = io.open(filename, "w")

      if not f then
        dt.print(
          "dtMediaWiki: unable to write preview: "
          .. tostring(err)
        )
        return
      end

      f:write(preview)
      f:write("\n")
      f:close()

      dt.print(
        "dtMediaWiki: Commons preview written to "
        .. filename
      )
    end
  }

-- widgets shown in lighttable
local export_widgets =
  dt.new_widget("box") {

    dt.new_widget("box") {
      orientation = "horizontal",

      dt.new_widget("label") {
        label = translate("Naming pattern:")
      },

      namepattern_widget
    },

    dt.new_widget("box") {
      orientation = "horizontal",
      filename_placeholder_widget
    },

    dt.new_widget("section_label") {
      label = translate(
        translate("Categories")
      )
    },

    global_categories_widget,

    dt.new_widget("section_label") {
      label = translate(
        "Templates"
      )
    },

    additional_wikitext_widget,
    --- preview_button,

    dt.new_widget("box") {
      orientation = "horizontal",

      dt.new_widget("label") {
        label = translate("Comment:")
      },

      comment_widget
    },

    dt.new_widget("box") {
      orientation = "horizontal",

      dt.new_widget("label") {
        label = translate("Language code:"),
        tooltip = translate(
          "Description language code (eg: en, fr, ...)."
        )
      },

      language_widget
    }
  }

-- Darktable target storage entry
if
    MediaWikiApi.login(
      dt.preferences.read(preferences_prefix, "username", "string"),
      dt.preferences.read(preferences_prefix, "password", "string")
    )
then
  -- https://docs.darktable.org/lua/stable/lua.api.manual/darktable/darktable.register_storage
  dt.register_storage(
    "mediawiki",
    "Wikimedia Commons",
    register_storage_store,
    register_storage_finalize,
    register_storage_supported,
    register_storage_initialize,
    export_widgets
  )
else
  msgout(translate("Unable to log into Wikimedia Commons, export disabled."))
end
